all: true
template: testify
packages:
  github.com/ShenokZlob/collector-service/internal/controllers:
    config:
      dir: ./internal/controllers/mocks
      filename: "mocks.go"
      pkgname: mocks
  github.com/ShenokZlob/collector-service/usecase/auth:
    config:
      dir: ./usecase/auth/mocks
      filename: "mocks.go"
      pkgname: mocks
